src/components/Footer/index.js
src/components/Footer/styles.js
yarn.lock

This PR updates the footer with proper links.

update footer with links

---

src/App.js
src/data/PageContent.js
src/pages/Arcade/index.js
src/pages/index.js

Arcade Page

---

src/components/Card/Card.js
src/components/Card/ScheduleCard.js
src/components/Header/index.js

Fixed overflow on schedule cards, adjusted card widths, removed button from layer

fixed overflow, removed button, adjusted widths of cards

---

src/components/Card/Card.js

changed buttons to secondary

---

src/components/Card/ScheduleCard.js

changed schedule card border radius to medium

change border radius to medium

---

src/components/Card/ScheduleCard.js
src/components/Footer/index.js
src/components/Footer/styles.js
src/components/HPEDevFooter/index.js
src/components/HPEDevFooter/styles.js
src/components/Header/index.js
src/components/Layout/index.js
src/components/Layout/styles.js
src/pages/Home/styles.js

Visual bugs fixes

---

src/components/Layout/index.js
src/data/CardData/PageContent.js
src/pages/Home/index.js
src/pages/StickerWall/index.js
src/pages/StickerWall/stickers.js

* took out content that is not ready 
* clean up prop types in sticker sheet

Ezmeral cleanup

---

src/pages/HackShackAttack/index.js
src/pages/HackShackAttack/scenes/GameOverScene.js
src/pages/HackShackAttack/scenes/HowToPlay.js
src/pages/HackShackAttack/scenes/PreloaderScene.js
src/pages/HackShackAttack/scenes/ThankYouScene.js
src/pages/HackShackAttack/scenes/TitleScene.js
src/pages/Home/index.js

Added a how to play scene to the game page
changed the color of the video link, and adjusted the space

added howtoplay scene to game change color and adjusted space of link

---

src/pages/Home/index.js
src/pages/StickerWall/index.js
src/pages/StickerWall/stickers.js
src/pages/StickerWall/styles.js
yarn.lock

* Clean up stickers sheet file

Cleanup stickers

---

src/App.js
src/pages/NewsletterTC/index.js
src/pages/index.js

This PR creates a Newsletter terms and conditions page referred from the HPE DEV portal Newsletter signup page.

newsletter terms conditions

---

src/pages/Competiton/index.js

This PR adds updated copy after legal edits

update copy with legal edits

---

src/pages/Home/index.js
src/pages/NewsletterTC/index.js

fix content

---

src/pages/StickerWall/index.js

fixes mobile view for stickerwall

fixed stickerwall mobile view

---

src/components/Card/ScheduleCard.js
src/data/ScheduleData/discover-events-wk2.json
src/pages/Schedule/index.js

change notebook data

---

src/data/ScheduleData/discover-events-wk3.json

This PR adds the notebook name field in the week3 JSON file

add notebook name

---

src/components/Card/ScheduleCard.js
src/data/ReplaysData/replays.json
src/data/ScheduleData/discover-events-wk5.json
src/pages/Home/index.js

This PR adds a week5 schedule with 4 challenges with a replay link to the challenge session.

update week5 schedule with only challenges

---

src/data/ReplaysData/replays.json
src/pages/ChallengeTC/index.js
src/pages/Competiton/index.js
src/pages/NewsletterTC/index.js

This PR updates replay video links, terms & conditions of Newsletter, Attack Game, and Challenges.

update replays terms and conditions

---

src/App.js
src/components/Card/ScheduleCard.js
src/components/Header/index.js
src/components/ScrollToTop/index.js
src/components/SideNav/index.js
src/components/Video/Video.js
src/components/Video/VideoList.js
src/data/CardData/PageContent.js
src/data/ScheduleData/schedule.json
src/pages/Home/index.js
src/pages/Replays/index.js

This PR adds the changes below
- Watch Replay on coding challenge replaced with “Learn more” and linked to C651 “Hack Shack challenges, are you ready to compete?” replay with autoplay.
- auto-scroll and autoplay of the selected video
- a separate link to specific videos
- update the copy on the home page

Scroll to top, autoplay and replay by ID

---

src/App.js
src/components/SideNav/index.js

This PR hides the challenges page while working on workshops on demand

hide challenges while working on workshops on demand

---

src/components/Card/ScheduleCard.js
src/components/Video/VideoList.js
src/data/CardData/PageContent.js
src/data/ReplaysData/replays.json
src/pages/ChallengeTC/index.js
src/pages/HackShackAttack/index.js
src/pages/HackShackAttack/scenes/HighScoreScene.js
src/pages/Home/index.js
src/pages/NewsletterTC/index.js
src/pages/WorkshopTC/index.js
yarn.lock

This PR updates home page copy, adds python and RUST replay videos, removes terms and conditions check for hack shack attack game.

Kubecon na 2020

---

src/pages/Home/index.js

Issue: Update home page munch and lunch card content per request from Didier

Update home page munch and lunch card content

---

src/pages/Replays/index.js

- Updates Replays page to use fetched data from `api/replays` endpoint https://github.com/hpe-dev-incubator/workshops_on_demand_server/pull/9
- Will display error message if the GET request is unsuccessful

Fetch data from Replays API

---

src/pages/Home/index.js

update munch and learn session5 card on home page

---

src/pages/Home/index.js

Update Home Munch & Lunch care to session 8

Update M&L card to session 6

---

public/index.html

Add meta tag values to make a test
<meta property="og:title"       content="Building a dynamic Machine Learning pipeline with KubeDirector" />
<meta property="og:description" content="Hurray! I finished the Dynamic Machine Learning Pipeline workshop" />
<meta property="og:image"       content="https://us-central1-grommet-designer.cloudfunctions.net/images/pramod-reddy-sareddy-hpe-com/badge1.png" />

add open graph tags title desc

---

src/pages/Home/index.js

This PR updates the hack shack home page copy.
Current message: Welcome to the Hack Shack, a place to collaborate and expand technology skills. Try our unique on-demand workshops or go on a virtual treasure hunt to discover a wealth of other resources and perhaps win a prize. 
New/original message: Welcome to the hack Shack. We offer many ways to collaborate and expand your skills. Try our technology Workshops-on-demand, for unique, hands-on learning experience.

update home page copy

---

src/components/Card/ScheduleCard.js

- The schedule card description hover gets stuck when user moves mouse too fast. 
- Use eventListener "mousemove" to track hover movement.

Fix ScheduleCard hover stuck screen when mouse moving too fast

---

src/data/CardData/PageContent.js
src/pages/Home/index.js

- Add treasure hunt card in home page and arcade page
- Update home page summary content

Add treasure hunt card for Discover 2021

---

src/pages/Home/index.js

Replace July munch & lunch home card with WOD card

Jay/remove July ml home card

---

src/pages/Workshops/template.js

- When tab is clicked, all card content will re-render to show card animation

Add keys to tabs to re-render tab content

---

src/pages/Home/index.js

- Update ML card to December session in home page

Update home card to munch and learn December

---

src/pages/Home/index.js

This PR updates the home page munch & learn card for January 2022.

update home page m&l card for jan 2022

---

src/pages/Home/index.js

This PR updates the home page intro video link to Youtube from Vimeo

change home page video from  vimeo to youtube
